### ISSUE TITLE
BUG with next JS

### ISSUE THREAD

**Issue by tamon-persol** [4lessandrodev/rich-domain#10]
**Describe the bug**
I try to use your library with nextJs but it doesn't seem to work.

**To Reproduce**
1. create a valueObject
2. `next dev`

**Screenshots**
<img width="851" alt="Screen Shot 2022-09-14 at 4 39 59" src="https://user-images.githubusercontent.com/60681425/189994226-d68e51e4-7898-4029-9d25-501b73c38296.png">

**Lib Version**
Example: rich-domain v1.1.0

**Additional context**

**Comment by tamon-persol** [comment]
<img width="405" alt="Screen Shot 2022-09-14 at 5 30 08" src="https://user-images.githubusercontent.com/60681425/190003276-b7b6033a-5e88-4105-b981-66ec3fd82684.png">

**Comment by 4lessandrodev** [comment]
Hey @tamon-persol thanks for reporting this bug.

This happens because nextJS generates a bundle on build the app and imports all libraries in a single package. To generate UUID the rich-domain lib uses cripto native in nodejs.

To fix this, the "rich-domain" library needs to expose Crypto. It is native to nodeJS version 14 as higher.

I will work on it.

**Comment by 4lessandrodev** [comment]
@tamon-persol  you can check the new version v1.12.0

I made this example
https://github.com/4lessandrodev/fix-next-rich-domain
