### ISSUE TITLE
Example: Domain Event Subscriptions with new TsEvents

### ISSUE THREAD

**Issue by mmmoli** [4lessandrodev/rich-domain#134]
Playing with the new `TsEvent` api.

Looks like it supersedes your [finance-app example](https://github.com/4lessandrodev/finance-project-ddd/blob/main/src/modules/user/domain/subscriptions/after-delete-user-account.subscription.ts).

Any tips for how to make subscriptions with the new API?

Thanks!

**Comment by 4lessandrodev** [comment]
Hey @mmmoli , thanks for reaching out! Since the "finance project", the library has undergone several upgrades, particularly in event handling. Take a look at the new approach for the eventHandler in this [example](https://github.com/4lessandrodev/ddd-app/blob/main/src/modules/product/domain/product-created.event.ts). There are various ways to add an event to the aggregate, but instead of dealing with global events, I suggest utilizing events directly within the aggregate instance. Check out this [example](https://github.com/4lessandrodev/ddd-app/blob/main/src/modules/product/app/use-cases/create-product.use-case.ts) to see how to add an event to an aggregate instance.

I hope this clears things up a bit. Feel free to ask if you have any further questions.

**Comment by 4lessandrodev** [comment]
Absolutely, glad to hear the examples have been helpful! 

For subscribing to Domain Events across different bounded contexts/modules with a "pull" mechanism, you typically need to establish communication between these contexts.

For handling events across different modules with a "pull" mechanism, consider leveraging the Node.js [Event emitter](https://nodejs.org/en/learn/asynchronous-work/the-nodejs-event-emitter). Similar to how events are handled in browser-based JavaScript, Node.js offers the EventEmitter class within its events module.

**Comment by 4lessandrodev** [comment]
# Testing something new

@mmmoli  Your question made me think a lot about the need for a tool that facilitates communication between contexts. Currently, the way it is structured, it is not possible to meet this requirement. That's why I'm thinking about implementing something similar to the draft below


```ts

import { Aggregate, Ok, Result, Context } from "rich-domain";

type Props = { name: string };

class User extends Aggregate<Props>{
    private constructor(props: Props) {
        super(props);
    }

    public static signUp(name: string): User {
        return new User({ name });
    }

    public static create(props: Props): Result<User> {
        return Ok(new User(props));
    }
}

// ------------
// Any Context - Subscribe
const context = Context.events();

type Model = { id: string; name: string; createdAt: Date; updatedAt: Date };

context.subscribe('signUp', (user: Model) => {
    console.log(user));
});


// ------------
// Account Context - Dispatch to Global Event
const user = User.signUp('Jane Doe');

context.dispatchEvent('signUp', user.toObject());


```


<img width="612" alt="image" src="https://github.com/4lessandrodev/rich-domain/assets/34426407/14186d43-d780-41bd-840d-cc86789774b5">


### Challenges

- How to maintain compatibility between browser and server?
- Do we keep or remove events controlled by the aggregate instance?
- Would it be better to keep the event added to the aggregate instance and fire the global event when calling the handler?

**Comment by mmmoli** [comment]
Love this. It's easy to see how I'd use it in the projects I'm building. 

- Would we get strong types?

- What happens in the context of fanning-out from a single lambda function? Would we cause a chain reaction of lambdas?

**Comment by 4lessandrodev** [comment]
## Some Points 

- **How to maintain compatibility between browser and server?**

For browser the lib add a CustomEvent to dom as global identified by provided name.

- **Do we keep or remove events controlled by the aggregate instance?**

the aggregate continues to have event management methods, these must be used for business rules of the context in which the aggregate is inserted

- **Would it be better to keep the event added to the aggregate instance and fire the global event when calling the handler?**

when triggering the event by the aggregate, the event for the global context will not be triggered automatically, it must be triggered by the handler or directly by the context event manually

- **Would we get strong types?**

the type of object to be sent in the parameters will be dynamic, and it is up to the developer to decide which type to send

- **What happens in the context of fanning-out from a single lambda function? Would we cause a chain reaction of lambdas?**

I'm still going to investigate

**Comment by 4lessandrodev** [comment]
### Testing version [1.20.3-beta.1](https://www.npmjs.com/package/rich-domain/v/1.20.3-beta.1)

Browser Suport:

![164c85ba-91b4-4711-bdf5-d1ae2343b244](https://github.com/4lessandrodev/rich-domain/assets/34426407/3740b8a1-d0f1-4577-9fef-3f5aec5944de)

[Github Project Sample](https://github.com/4lessandrodev/fix-next-rich-domain)

**Comment by 4lessandrodev** [comment]
### Testing version [1.20.3-beta.1](https://www.npmjs.com/package/rich-domain/v/1.20.3-beta.1)

Server NodeJS support 

![image](https://github.com/4lessandrodev/rich-domain/assets/34426407/88592fb2-e887-4a63-9f3a-732e85e25fba)

[GIthub Project Sample](https://github.com/4lessandrodev/ddd-app/blob/main/src/contexts/product/domain/product-created.event.ts)
